// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package database

import (
	"github.com/google/uuid"
)

type AdminsAssociation struct {
	ClientID uuid.UUID
	ApiID    uuid.UUID
}

type Api struct {
	ID   uuid.UUID
	Name string
	Url  string
}

type Client struct {
	ID   uuid.UUID
	Name string
}

type Route struct {
	ID     uuid.UUID
	Method string
	Path   string
	ApiID  uuid.UUID
}

type RoutesAssociation struct {
	ClientID uuid.UUID
	RouteID  uuid.UUID
}
