// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: queries.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getApiRoutes = `-- name: GetApiRoutes :many
SELECT id, path, method
FROM routes 
WHERE api_id = $1
`

type GetApiRoutesRow struct {
	ID     uuid.UUID
	Path   string
	Method string
}

func (q *Queries) GetApiRoutes(ctx context.Context, apiID uuid.UUID) ([]GetApiRoutesRow, error) {
	rows, err := q.db.Query(ctx, getApiRoutes, apiID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetApiRoutesRow
	for rows.Next() {
		var i GetApiRoutesRow
		if err := rows.Scan(&i.ID, &i.Path, &i.Method); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getApis = `-- name: GetApis :many
SELECT id, url
FROM apis
`

type GetApisRow struct {
	ID  uuid.UUID
	Url string
}

func (q *Queries) GetApis(ctx context.Context) ([]GetApisRow, error) {
	rows, err := q.db.Query(ctx, getApis)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetApisRow
	for rows.Next() {
		var i GetApisRow
		if err := rows.Scan(&i.ID, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClients = `-- name: GetClients :many
SELECT name
FROM clients
`

func (q *Queries) GetClients(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRouteClients = `-- name: GetRouteClients :many
SELECT c.name 
FROM routes_association AS ra 
JOIN clients AS c ON ra.client_id=c.id 
WHERE route_id = $1
`

func (q *Queries) GetRouteClients(ctx context.Context, routeID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getRouteClients, routeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
