version: "3.9"

services:
  server:
    profiles: [ 'all', 'dev' ]
    build:
      context: .
    environment:
      POSTGRES_URL: postgres://postgres:postgres@postgres/authdb
      JWT_PUBLIC_KEY: xxx
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  postgres:
    profiles: [ 'all', 'dev', 'test' ]
    image: postgres:14.5-alpine3.16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authdb
    ports:
      - "5432:5432"
    configs:
      - source: postgres-schema
        target: /docker-entrypoint-initdb.d/schema.sql

configs:
  postgres-schema:
    file: sql/schema.sql
