version: "3"

tasks:
  stop:
    cmds:
      - docker-compose --profile all rm -sf
  
  start-dev:
    cmds: 
      - docker-compose --profile dev up --build
      - defer: {task: stop}

  setup-test:
    cmds: 
      - docker-compose --profile test up --build -d

  pretty:
    cmds:
      - go fmt ./...
      - go mod tidy
      - go clean
  
  validate:
    cmds: 
      - golangci-lint run
  
  test:
    cmds:
      - go test -v -coverprofile cover.out ./...
      - go tool cover -html=cover.out -o cover.html

  build:
    cmds:
      - go build -race -o main.out cmd/service/main.go
  
  run:
    cmds:
      - go run cmd/service/main.go